spring:
  datasource: 
        name: test
        url: jdbc:mysql://127.0.0.1:3306/testboot
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
  
#jdbc.driverClassName=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://127.0.0.1:3306/testboot?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#jdbc.username=root
#jdbc.password=root

#指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名（看后边的UserMapper.xml介绍）
#mybatis.typeAliasesPackage=com.example.entity
#指定*Mapper.xml的位置
#mybatis.mapperLocations=classpath:mapper/*.xml
mybatis:
  mapper-locations: mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.entity  # 注意：对应实体类的路径
  
logging:
  level: 
    com.example.mapper: DEBUG
#禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
#spring.thymeleaf.cache=false
#完全关闭重启支持
#spring.devtools.restart.enabled=false
#排除那个目录的文件不需要restart
#spring.devtools.restart.exclude=public/**,static/**
#添加那个目录的文件需要restart
#spring.devtools.restart.additional-paths=src/main/java